services:
  intern-db:
    image: postgres:16
    environment:
      POSTGRES_DB: CampusConnect
      POSTGRES_USER: SuperUser
      POSTGRES_PASSWORD: dvTRBqRJkRiebPIgiYKLYBQAdwlsWWmF
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  
  intern-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./Application:/var/www/html
    depends_on:
      - intern-db
    environment:
      - DB_HOST=intern-db
      - DB_NAME=CampusConnect
      - DB_USER=SuperUser
      - DB_PASS=dvTRBqRJkRiebPIgiYKLYBQAdwlsWWmF
      - DB_PORT=5432
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: